### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by wlbksy**
fix requirements

### CODE REVIEW

**Comment by wlbksy** [comment]
Currently I can't acquire band data without this dependency using geotiff package. It would complain lacking imagecodecs on my macOS miniconda.
I've no idea why this is dependent, but installing this fixed the command line complaining.

**Comment by KipCrossing** [comment]
@wlbksy @Zeitsperre  Looks like the latest version of the `tifffile` package relies on `imagecodecs`; see [here](https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/setup.py#L98). 

So adding it to our requirements would make it redundant anyway. Not sure why it didn't install for you @wlbksy. What version of python are you using?

**Comment by KipCrossing** [comment]
It looks like the `tifffile` package wants the user to take care of installing `imagecodecs`

see [here](https://github.com/cgohlke/tifffile/blob/375d97f62df6482142b51f1b38a49bdd24d18a60/tifffile/tifffile.py#L773)

So perhaps it's now up to us to ensure this via this PR. I'll look into it a bit more.

**Comment by KipCrossing** [comment]
Look's like the import bug was introduced to `tifffile` in version [2022.4.28](https://github.com/cgohlke/tifffile/tree/v2022.4.28) where pretty much all the import attempts fail. We can restrict the version of `tifffile` to an earlier version

**Comment by KipCrossing** [comment]
Closed by #51

**Pull request closed without merging**
