### PR TITLE
Add precommit configuration

### LINKED ISSUE #46: Use a pre-commit configuration
When introducing changes to the library, ensuring that we don't introduce regressions on commit is an action that can be automated using existing checker utilities. One particular tool I use in a multitude of projects is [`pre-commit`](https://pre-commit.com/) and its CI counterpart (https://pre-commit.ci/). 

The types of checks we can perform are numerous:
- Checking the validity of the source files (`check-manifest`)
- Static typing (mypy)
- Black code formatting
- Documentation references
- etc.

I will open a PR with a handful of checks based on existing code practices, but if we want to adopt more, the list of potential checks is quite extensive (https://pre-commit.com/hooks.html).

### PR DESCRIPTION
**Pull request by Zeitsperre**
Closes #46.

## What does this introduce?

Pre-commit is a tool for running checks on code changes prior to committing them, preventing errors and inconsistencies from being introduced. I've added a pretty simple configuration that does a handful of things:
 - Runs black and a subset of black-compatible flake8 checks over the code base
 - Removes trailing whitespaces and adds an empty newline at the end of files
 - Sorts import statements consistent with Black
 - Checks for redundant `# noqa` statements

I've also added, but commented out, a few checks that require some effort.
- Check Manifest file for any missing/unaccounted files (requires manifest file made in #47.)
- PyDocStyle is a grammatical linter for writing consistent docstrings. Many changes needed. Willing to open more PRs for this.

### CODE REVIEW

**Comment by KipCrossing** [comment]
@Zeitsperre What's the best way to test this on my local? 

Should we add a check for mypy too?

#47 has been approved, so feel free to merge

PyDocStyle sounds very opinionated, we should discuss the advantages in another PR.

**Comment by Zeitsperre** [comment]
> @Zeitsperre What's the best way to test this on my local?

To configure pre-commit in the repo:
```
$ pip install pre-commit
$ pre-commit install
```
This will make it so that anytime you commit a file, the pre-commit linters and checkers will run automatically.

To run the checks manually:
```
$ pre-commit run --all-files
```

> Should we add a check for mypy too?

We can! And will do!

> #47 has been approved, so feel free to merge

Thanks!

> PyDocStyle sounds very opinionated, we should discuss the advantages in another PR.

Sounds good to me. The documentation conventions/style can be different depending on preferences. I'm partial to [numpy-docstyle conventions](https://numpydoc.readthedocs.io/en/latest/format.html), but [others](http://www.pydocstyle.org/en/stable/error_codes.html?#default-conventions) are supported. Will open an issue concerning it.

**Comment by KipCrossing** [comment]
Should we add `pre-commit` as a dev requirement? 

And perhaps some instructions on how to use it?

Maybe there's a way to initiate `pre-commit install` via the `setup.py` when a dev install is run.

**Comment by KipCrossing** [comment]
BTW, I've tested it and it looks like it will be a handy tool; especially to save some time when waiting for CI on GitHub just for it to fail (eg mypy).

**Review by KipCrossing — APPROVED** [review]
Feel free to merge - but at the very least we should mention the pre-commit option in the CONTRIBUTING doc

**Comment by Zeitsperre** [comment]
Hi @KipCrossing sorry for the delay!

In terms of time-saving, pre-commit is fantastic, and I've integrated it into many of the projects I help run. I can copy-paste some explanatory flavour text into the docs somewhere in this PR.

I like your idea of installing pre-commit when one makes a `dev` install. I know there's a way to do this. Can certainly look into it.

**Pull request merged**
